services:
  postgres:
    container_name: postgres
    image: "postgres"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
  itmo-task:
    depends_on:
      - postgres
    build: .
    ports:
      - ${ITMO_TASK_PORT}:8080
    environment:
      - ITMO_TASK_DATABASE_URL=${ITMO_TASK_DATABASE_URL}
    restart: unless-stopped
volumes:
  postgres: